sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - SYMFONY_PHPUNIT_VERSION=7.4
    - SYMFONY_LOWEST=

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: SYMFONY_LOWEST="3.4.*

install:
  - composer install --prefer-dist
  - if [ "$SYMFONY_LOWEST" != "" ]; then composer require symfony/framework-bundle:$SYMFONY_LOWEST --dev; fi

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/simple-phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls
