image: php:7.2.2

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y zlib1g-dev && docker-php-ext-install zip && rm -r /var/lib/apt/lists/*
          - php -r "readfile('https://getcomposer.org/installer');" | php && mv composer.phar /usr/local/bin/composer
          - composer install
          - vendor/bin/simple-phpunit --log-junit ./test-reports/junit.xml
